/**
 * ISO 4217 currency table: the reviewed snapshot behind `CurrencyCode` (design section 3.2).
 *
 * Source: ISO 4217 List One ("Current currency & funds code list") published by SIX, the ISO 4217
 * maintenance agency. Snapshot taken on 2026-10-09 from the `datasets/currency-codes` mirror of
 * that list (`data/codes-all.csv`, rows without a withdrawal date); to be re-checked against
 * SIX's `list-one.xml` at the next snapshot update.
 *
 * Contents: every active alphabetic code with a numeric minor unit. Excluded, because ISO gives
 * them no minor unit ("N.A."): precious metals (XAU, XAG, XPD, XPT), bond-market units
 * (XBA-XBD), XDR, XSU, XUA, the test code XTS and XXX.
 *
 * Deliberate exception: BGN. Bulgaria adopted the euro on 2026-01-01 and ISO withdrew the lev
 * (2026-01). It stays in this table so that historical invoices in BGN remain readable.
 *
 * Updating this file is a reviewed change with its own test diff (`currency.test.ts`), never an
 * automatic job.
 */
export const CURRENCY_DATA = Object.freeze({
  AED: { numeric: "784", exponent: 2, name: "UAE Dirham" },
  AFN: { numeric: "971", exponent: 2, name: "Afghani" },
  ALL: { numeric: "008", exponent: 2, name: "Lek" },
  AMD: { numeric: "051", exponent: 2, name: "Armenian Dram" },
  AOA: { numeric: "973", exponent: 2, name: "Kwanza" },
  ARS: { numeric: "032", exponent: 2, name: "Argentine Peso" },
  AUD: { numeric: "036", exponent: 2, name: "Australian Dollar" },
  AWG: { numeric: "533", exponent: 2, name: "Aruban Florin" },
  AZN: { numeric: "944", exponent: 2, name: "Azerbaijan Manat" },
  BAM: { numeric: "977", exponent: 2, name: "Convertible Mark" },
  BBD: { numeric: "052", exponent: 2, name: "Barbados Dollar" },
  BDT: { numeric: "050", exponent: 2, name: "Taka" },
  BGN: { numeric: "975", exponent: 2, name: "Bulgarian Lev" },
  BHD: { numeric: "048", exponent: 3, name: "Bahraini Dinar" },
  BIF: { numeric: "108", exponent: 0, name: "Burundi Franc" },
  BMD: { numeric: "060", exponent: 2, name: "Bermudian Dollar" },
  BND: { numeric: "096", exponent: 2, name: "Brunei Dollar" },
  BOB: { numeric: "068", exponent: 2, name: "Boliviano" },
  BOV: { numeric: "984", exponent: 2, name: "Mvdol" },
  BRL: { numeric: "986", exponent: 2, name: "Brazilian Real" },
  BSD: { numeric: "044", exponent: 2, name: "Bahamian Dollar" },
  BTN: { numeric: "064", exponent: 2, name: "Ngultrum" },
  BWP: { numeric: "072", exponent: 2, name: "Pula" },
  BYN: { numeric: "933", exponent: 2, name: "Belarusian Ruble" },
  BZD: { numeric: "084", exponent: 2, name: "Belize Dollar" },
  CAD: { numeric: "124", exponent: 2, name: "Canadian Dollar" },
  CDF: { numeric: "976", exponent: 2, name: "Congolese Franc" },
  CHE: { numeric: "947", exponent: 2, name: "WIR Euro" },
  CHF: { numeric: "756", exponent: 2, name: "Swiss Franc" },
  CHW: { numeric: "948", exponent: 2, name: "WIR Franc" },
  CLF: { numeric: "990", exponent: 4, name: "Unidad de Fomento" },
  CLP: { numeric: "152", exponent: 0, name: "Chilean Peso" },
  CNY: { numeric: "156", exponent: 2, name: "Yuan Renminbi" },
  COP: { numeric: "170", exponent: 2, name: "Colombian Peso" },
  COU: { numeric: "970", exponent: 2, name: "Unidad de Valor Real" },
  CRC: { numeric: "188", exponent: 2, name: "Costa Rican Colon" },
  CUP: { numeric: "192", exponent: 2, name: "Cuban Peso" },
  CVE: { numeric: "132", exponent: 2, name: "Cabo Verde Escudo" },
  CZK: { numeric: "203", exponent: 2, name: "Czech Koruna" },
  DJF: { numeric: "262", exponent: 0, name: "Djibouti Franc" },
  DKK: { numeric: "208", exponent: 2, name: "Danish Krone" },
  DOP: { numeric: "214", exponent: 2, name: "Dominican Peso" },
  DZD: { numeric: "012", exponent: 2, name: "Algerian Dinar" },
  EGP: { numeric: "818", exponent: 2, name: "Egyptian Pound" },
  ERN: { numeric: "232", exponent: 2, name: "Nakfa" },
  ETB: { numeric: "230", exponent: 2, name: "Ethiopian Birr" },
  EUR: { numeric: "978", exponent: 2, name: "Euro" },
  FJD: { numeric: "242", exponent: 2, name: "Fiji Dollar" },
  FKP: { numeric: "238", exponent: 2, name: "Falkland Islands Pound" },
  GBP: { numeric: "826", exponent: 2, name: "Pound Sterling" },
  GEL: { numeric: "981", exponent: 2, name: "Lari" },
  GHS: { numeric: "936", exponent: 2, name: "Ghana Cedi" },
  GIP: { numeric: "292", exponent: 2, name: "Gibraltar Pound" },
  GMD: { numeric: "270", exponent: 2, name: "Dalasi" },
  GNF: { numeric: "324", exponent: 0, name: "Guinean Franc" },
  GTQ: { numeric: "320", exponent: 2, name: "Quetzal" },
  GYD: { numeric: "328", exponent: 2, name: "Guyana Dollar" },
  HKD: { numeric: "344", exponent: 2, name: "Hong Kong Dollar" },
  HNL: { numeric: "340", exponent: 2, name: "Lempira" },
  HTG: { numeric: "332", exponent: 2, name: "Gourde" },
  HUF: { numeric: "348", exponent: 2, name: "Forint" },
  IDR: { numeric: "360", exponent: 2, name: "Rupiah" },
  ILS: { numeric: "376", exponent: 2, name: "New Israeli Sheqel" },
  INR: { numeric: "356", exponent: 2, name: "Indian Rupee" },
  IQD: { numeric: "368", exponent: 3, name: "Iraqi Dinar" },
  IRR: { numeric: "364", exponent: 2, name: "Iranian Rial" },
  ISK: { numeric: "352", exponent: 0, name: "Iceland Krona" },
  JMD: { numeric: "388", exponent: 2, name: "Jamaican Dollar" },
  JOD: { numeric: "400", exponent: 3, name: "Jordanian Dinar" },
  JPY: { numeric: "392", exponent: 0, name: "Yen" },
  KES: { numeric: "404", exponent: 2, name: "Kenyan Shilling" },
  KGS: { numeric: "417", exponent: 2, name: "Som" },
  KHR: { numeric: "116", exponent: 2, name: "Riel" },
  KMF: { numeric: "174", exponent: 0, name: "Comorian Franc" },
  KPW: { numeric: "408", exponent: 2, name: "North Korean Won" },
  KRW: { numeric: "410", exponent: 0, name: "Won" },
  KWD: { numeric: "414", exponent: 3, name: "Kuwaiti Dinar" },
  KYD: { numeric: "136", exponent: 2, name: "Cayman Islands Dollar" },
  KZT: { numeric: "398", exponent: 2, name: "Tenge" },
  LAK: { numeric: "418", exponent: 2, name: "Lao Kip" },
  LBP: { numeric: "422", exponent: 2, name: "Lebanese Pound" },
  LKR: { numeric: "144", exponent: 2, name: "Sri Lanka Rupee" },
  LRD: { numeric: "430", exponent: 2, name: "Liberian Dollar" },
  LSL: { numeric: "426", exponent: 2, name: "Loti" },
  LYD: { numeric: "434", exponent: 3, name: "Libyan Dinar" },
  MAD: { numeric: "504", exponent: 2, name: "Moroccan Dirham" },
  MDL: { numeric: "498", exponent: 2, name: "Moldovan Leu" },
  MGA: { numeric: "969", exponent: 2, name: "Malagasy Ariary" },
  MKD: { numeric: "807", exponent: 2, name: "Denar" },
  MMK: { numeric: "104", exponent: 2, name: "Kyat" },
  MNT: { numeric: "496", exponent: 2, name: "Tugrik" },
  MOP: { numeric: "446", exponent: 2, name: "Pataca" },
  MRU: { numeric: "929", exponent: 2, name: "Ouguiya" },
  MUR: { numeric: "480", exponent: 2, name: "Mauritius Rupee" },
  MVR: { numeric: "462", exponent: 2, name: "Rufiyaa" },
  MWK: { numeric: "454", exponent: 2, name: "Malawi Kwacha" },
  MXN: { numeric: "484", exponent: 2, name: "Mexican Peso" },
  MXV: { numeric: "979", exponent: 2, name: "Mexican Unidad de Inversion (UDI)" },
  MYR: { numeric: "458", exponent: 2, name: "Malaysian Ringgit" },
  MZN: { numeric: "943", exponent: 2, name: "Mozambique Metical" },
  NAD: { numeric: "516", exponent: 2, name: "Namibia Dollar" },
  NGN: { numeric: "566", exponent: 2, name: "Naira" },
  NIO: { numeric: "558", exponent: 2, name: "Cordoba Oro" },
  NOK: { numeric: "578", exponent: 2, name: "Norwegian Krone" },
  NPR: { numeric: "524", exponent: 2, name: "Nepalese Rupee" },
  NZD: { numeric: "554", exponent: 2, name: "New Zealand Dollar" },
  OMR: { numeric: "512", exponent: 3, name: "Rial Omani" },
  PAB: { numeric: "590", exponent: 2, name: "Balboa" },
  PEN: { numeric: "604", exponent: 2, name: "Sol" },
  PGK: { numeric: "598", exponent: 2, name: "Kina" },
  PHP: { numeric: "608", exponent: 2, name: "Philippine Peso" },
  PKR: { numeric: "586", exponent: 2, name: "Pakistan Rupee" },
  PLN: { numeric: "985", exponent: 2, name: "Zloty" },
  PYG: { numeric: "600", exponent: 0, name: "Guarani" },
  QAR: { numeric: "634", exponent: 2, name: "Qatari Rial" },
  RON: { numeric: "946", exponent: 2, name: "Romanian Leu" },
  RSD: { numeric: "941", exponent: 2, name: "Serbian Dinar" },
  RUB: { numeric: "643", exponent: 2, name: "Russian Ruble" },
  RWF: { numeric: "646", exponent: 0, name: "Rwanda Franc" },
  SAR: { numeric: "682", exponent: 2, name: "Saudi Riyal" },
  SBD: { numeric: "090", exponent: 2, name: "Solomon Islands Dollar" },
  SCR: { numeric: "690", exponent: 2, name: "Seychelles Rupee" },
  SDG: { numeric: "938", exponent: 2, name: "Sudanese Pound" },
  SEK: { numeric: "752", exponent: 2, name: "Swedish Krona" },
  SGD: { numeric: "702", exponent: 2, name: "Singapore Dollar" },
  SHP: { numeric: "654", exponent: 2, name: "Saint Helena Pound" },
  SLE: { numeric: "925", exponent: 2, name: "Leone" },
  SOS: { numeric: "706", exponent: 2, name: "Somali Shilling" },
  SRD: { numeric: "968", exponent: 2, name: "Surinam Dollar" },
  SSP: { numeric: "728", exponent: 2, name: "South Sudanese Pound" },
  STN: { numeric: "930", exponent: 2, name: "Dobra" },
  SVC: { numeric: "222", exponent: 2, name: "El Salvador Colon" },
  SYP: { numeric: "760", exponent: 2, name: "Syrian Pound" },
  SZL: { numeric: "748", exponent: 2, name: "Lilangeni" },
  THB: { numeric: "764", exponent: 2, name: "Baht" },
  TJS: { numeric: "972", exponent: 2, name: "Somoni" },
  TMT: { numeric: "934", exponent: 2, name: "Turkmenistan New Manat" },
  TND: { numeric: "788", exponent: 3, name: "Tunisian Dinar" },
  TOP: { numeric: "776", exponent: 2, name: "Pa’anga" },
  TRY: { numeric: "949", exponent: 2, name: "Turkish Lira" },
  TTD: { numeric: "780", exponent: 2, name: "Trinidad and Tobago Dollar" },
  TWD: { numeric: "901", exponent: 2, name: "New Taiwan Dollar" },
  TZS: { numeric: "834", exponent: 2, name: "Tanzanian Shilling" },
  UAH: { numeric: "980", exponent: 2, name: "Hryvnia" },
  UGX: { numeric: "800", exponent: 0, name: "Uganda Shilling" },
  USD: { numeric: "840", exponent: 2, name: "US Dollar" },
  USN: { numeric: "997", exponent: 2, name: "US Dollar (Next day)" },
  UYI: { numeric: "940", exponent: 0, name: "Uruguay Peso en Unidades Indexadas (UI)" },
  UYU: { numeric: "858", exponent: 2, name: "Peso Uruguayo" },
  UYW: { numeric: "927", exponent: 4, name: "Unidad Previsional" },
  UZS: { numeric: "860", exponent: 2, name: "Uzbekistan Sum" },
  VED: { numeric: "926", exponent: 2, name: "Bolívar Soberano" },
  VES: { numeric: "928", exponent: 2, name: "Bolívar Soberano" },
  VND: { numeric: "704", exponent: 0, name: "Dong" },
  VUV: { numeric: "548", exponent: 0, name: "Vatu" },
  WST: { numeric: "882", exponent: 2, name: "Tala" },
  XAD: { numeric: "396", exponent: 2, name: "Arab Accounting Dinar" },
  XAF: { numeric: "950", exponent: 0, name: "CFA Franc BEAC" },
  XCD: { numeric: "951", exponent: 2, name: "East Caribbean Dollar" },
  XCG: { numeric: "532", exponent: 2, name: "Caribbean Guilder" },
  XOF: { numeric: "952", exponent: 0, name: "CFA Franc BCEAO" },
  XPF: { numeric: "953", exponent: 0, name: "CFP Franc" },
  YER: { numeric: "886", exponent: 2, name: "Yemeni Rial" },
  ZAR: { numeric: "710", exponent: 2, name: "Rand" },
  ZMW: { numeric: "967", exponent: 2, name: "Zambian Kwacha" },
  ZWG: { numeric: "924", exponent: 2, name: "Zimbabwe Gold" },
} as const);
